accessID: d83DS2qGck7UjhtfmHw2
accessKey: >-
  lma_5qfcP7v86a_~53fGN^x7VNJQegi9%X7w-dhar^i[xC5f2M4TPEEN4tcm25zALMzBiOGEwNGItNmE1OC00Y2QxLWFmODMtZDEzMWYxYTk2YWUwL0nA9vl
account: fujitsu
debug: false
enableRBAC: true
etcdDiscoveryToken: ''
imageRepository: logicmonitor/collectorset-controller
imageTag: v3
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
