accessID: FcmV83649hRzB3q8Y3wq
accessKey: >-
  lma_[s4C3XjsFyf-jS853v[wM4{kA%^{PauWL-}ZK3b~CvX^Mm[6f8-yf5k+}Zb8LM2UwYjk1MTEtMGNhMS00N2E1LTg3ODMtMWMwY2I0MzgzNzJjL092SLB
account: fujitsusandbox
debug: false
enableRBAC: true
etcdDiscoveryToken: ''
imageRepository: logicmonitor/collectorset-controller
imageTag: v3
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
