accessID: 4dBhL5638xh6ecuT4mhh
accessKey: >-
  lma_2KPuW^q4{X[(9W(x^55F]j4{L4]Qs}]982SZF]84^2-gp[A)Rz~54^D%=+(HLMzBiOGEwNGItNmE1OC00Y2QxLWFmODMtZDEzMWYxYTk2YWUwL3H3zxD
account: fujitsu
debug: false
enableRBAC: true
etcdDiscoveryToken: ''
imageRepository: logicmonitor/collectorset-controller
imageTag: v3
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
