accessID: 26nNRy4Z3KZ6cWQTfcIF
accessKey: >-
  lma_~FWm=~qaK2+keBk8uK25j]Rani2AzxX4Cyx~5a6^8z%Y=55Ufcb}F2]4A9+7LMzBiOGEwNGItNmE1OC00Y2QxLWFmODMtZDEzMWYxYTk2YWUwL4hq6HI
account: fujitsu
debug: false
enableRBAC: true
etcdDiscoveryToken: ''
imageRepository: logicmonitor/collectorset-controller
imageTag: v3
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
